import { DecorativeIcon } from '../components/DecorativeIcon';
export function About(){return (    <section id="about" className="about-page" aria-labelledby="about-title">
      <a className="back-link" href="#">Back home</a>
      <div className="about-intro"><div className="eyebrow">A SMALL IDEA, FOR THE PEOPLE YOU MISS</div><h1 id="about-title">Miles apart.<br /><em>Still together.</em></h1><p>For the dates that happen through a screen.<br />The best friends in different time zones.<br />The people you wish were a little closer.</p></div>
      <div className="about-story"><span className="about-mark" aria-hidden="true"><DecorativeIcon /></span><div><h2>A photobooth without<br /><em>the same postcode.</em></h2><p>Some of the nicest memories are the unplanned ones: a silly face, a laugh you couldn’t hold in, one more photo before you go. Distance shouldn’t mean missing out on those little rituals.</p><p>Together is an online photobooth being built for couples and friends who can’t step into a booth side by side. The plan is to bring two webcams into one shared moment, then turn that moment into a photocard you can make your own.</p></div></div>
      <div className="about-notes"><article><span className="step-number">01</span><h3>Made for your people.</h3><p>A shared link, a little time together, and room to be yourselves. No profiles to build or feeds to scroll.</p></article><article><span className="step-number">02</span><h3>A keepsake that feels like you.</h3><p>Pick a mood, choose a frame color, and add a few words. A small souvenir of being together.</p></article><article><span className="step-number">03</span><h3>Built with a little curiosity.</h3><p>This is a student portfolio project, created while learning computer science and software engineering with AI assistance.</p></article></div>
      <div className="about-preview"><div><div className="eyebrow">WHERE WE ARE TODAY</div><h2>A little work <em>in progress.</em></h2><p>You can explore the booth with sample photos, try filters and frames, and download a sample strip. Solo webcam capture is available; shared sessions and invitation links are the next chapter.</p></div><a className="primary" href="#booth">Take the photos now</a></div>
    </section>
);}
