import { HeroArt } from '../components/HeroArt';
export function Home(){return (    <div id="home">
      <section className="hero" aria-labelledby="hero-title">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> YOUR PEOPLE. ANY DISTANCE.</div><h1 id="hero-title">Different places.<br />Same <em>little</em><br /><span className="last-line">moment.<span className="title-star" aria-hidden="true">✳</span></span></h1><p>An online photobooth for the people<br className="desktop-break" /> you wish were right beside you.</p><a className="primary" href="#booth">Take the photos now</a><div className="hero-note"><span aria-hidden="true">♡</span> No sign-ups. Just show up.</div></div>
        <HeroArt />
      </section>
      <div className="ribbon" aria-label="A moment worth keeping"><span>For the long-distance lovers</span><b aria-hidden="true">✳</b><span>The across-the-world besties</span><b aria-hidden="true">✳</b><span>The just-one-more-photo people</span><b aria-hidden="true">✳</b></div>
      <section id="how-it-works" className="how"><div className="section-intro"><div className="eyebrow">CLOSE, IN THREE LITTLE STEPS</div><h2>A date. A catch-up.<br /><em>A reason to smile.</em></h2><p>Bring your favorite person.<br />We’ll bring the photobooth.</p></div><div className="steps"><article><span className="step-number">01</span><div><h3>Send a little invitation.</h3><p>Start a booth and share the link. Your person joins from wherever they are.</p></div><span className="step-icon" aria-hidden="true">↗</span></article><article><span className="step-number">02</span><div><h3>Make a face. Make a memory.</h3><p>Pick a filter, get in frame, and let the countdown do its thing.</p></div><span className="step-icon" aria-hidden="true">✳</span></article><article><span className="step-number">03</span><div><h3>Keep a piece of together.</h3><p>Make the photocard yours. Save it, print it, or make it your new wallpaper.</p></div><span className="step-icon" aria-hidden="true">♡</span></article></div></section>
      <section className="closing"><div className="eyebrow">THE MILES CAN WAIT A MINUTE.</div><h2>Meet me <em>in the booth.</em></h2><a className="primary" href="#booth">Take the photos now</a></section>
      <section className="faq" id="faq" aria-labelledby="faq-title">
        <div className="faq-intro"><div className="eyebrow">A FEW LITTLE ANSWERS</div><h2 id="faq-title">Wondering<br /><em>about something?</em></h2><p>Before you step into the booth.</p></div>
        <div className="faq-list">
          <details><summary>How does Together work?<span aria-hidden="true">+</span></summary><div className="faq-answer"><p>The idea is simple: open a booth, send your person a link, and take photos together from two webcams. Then choose your filters, personalize the strip, and save it. Right now, you can take solo camera photos or try sample photos. Shared rooms with a friend are coming next.</p></div></details>
          <details><summary>Are my photos and data safe?<span aria-hidden="true">+</span></summary><div className="faq-answer"><p>Camera access only starts when you choose “Turn camera on.” Photos, captions, and edits stay in this browser tab; this app does not upload them. Your photocard is created on your device when you download or print it. Refreshing clears your edits. The site host and font provider may receive normal web-request information. We’ll explain live-session privacy before that feature launches.</p></div></details>
          <details><summary>Do I need to sign up or pay?<span aria-hidden="true">+</span></summary><div className="faq-answer"><p>No account or payment is required to try this preview or download a sample strip. Together is a student portfolio project, with a free, no-signup photobooth as the goal.</p></div></details>
          <details><summary>Can I use it on my phone?<span aria-hidden="true">+</span></summary><div className="faq-answer"><p>Yes, Together adapts to phones, tablets, and desktops. Open your invitation in your browser and allow camera access, or choose to upload existing photos.</p></div></details>
          <details><summary>Can I save or print my photocard?<span aria-hidden="true">+</span></summary><div className="faq-answer"><p>Yes. Choose PNG or JPG in the booth, then save your sample strip. You can keep the file, share it yourself, or print it. Your download includes the photos from your session, in the layout and style you chose.</p></div></details>
        </div>
      </section>
      <footer><a className="wordmark" href="#">together<span className="brand-dot">✳</span></a><span>A little closer. Wherever you are.</span><span className="prototype-label">DESIGN PREVIEW · 2026</span></footer>
    </div>
);}
