(() => {
  const {layouts,filters,move,captureTargets,replaceShot,filterPixels}=BoothCore;
  const cardDesigns={"breaking-news":{"name":"Breaking News","size":[799,1969],"crop":[0,0,799,1969],"slots":[{"x":64,"y":570,"w":671,"h":384,"r":0},{"x":64,"y":994,"w":671,"h":380,"r":0},{"x":64,"y":1413,"w":671,"h":382,"r":0}],"src":"public/a-breaking-news.png"},"catch-yours":{"name":"Catch Yours","size":[1030,1526],"crop":[0,0,514,1526],"slots":[{"x":62,"y":246,"w":373,"h":276,"r":0,"poly":[[62,261],[424,246],[435,506],[71,522]]},{"x":64,"y":598,"w":381,"h":287,"r":0,"poly":[[85,598],[445,628],[424,885],[64,858]]},{"x":63,"y":960,"w":366,"h":265,"r":0,"poly":[[68,960],[429,966],[425,1225],[63,1220]]}],"src":"public/a-catch-yours.png"},"clapper-filmstrip":{"name":"Clapper Filmstrip","size":[1090,1443],"crop":[53,33,446,1329],"slots":[{"x":115,"y":338,"w":325,"h":327,"r":0},{"x":115,"y":674,"w":325,"h":326,"r":0},{"x":115,"y":1009,"w":325,"h":329,"r":0}],"src":"public/a-clapper-filmstrip.png"},"endless-moments":{"name":"Endless Moments","size":[1024,1536],"crop":[228,12,568,1512],"slots":[{"x":272,"y":97,"w":481,"h":364,"r":0},{"x":272,"y":501,"w":481,"h":363,"r":0},{"x":272,"y":903,"w":481,"h":360,"r":0}],"mask":"cream","src":"public/a-endless-moments.png"},"film-negative":{"name":"Film Negative","size":[1024,1536],"crop":[248,20,528,1494],"slots":[{"x":314,"y":41,"w":396,"h":395,"r":21},{"x":314,"y":454,"w":396,"h":388,"r":21},{"x":314,"y":860,"w":396,"h":379,"r":21}],"src":"public/a-film-negative.png"},"movie-time":{"name":"Movie Time","size":[1085,1449],"crop":[303,12,480,1397],"slots":[{"x":346,"y":226,"w":397,"h":286,"r":0},{"x":346,"y":520,"w":397,"h":278,"r":0},{"x":346,"y":807,"w":397,"h":280,"r":0}],"src":"public/a-movie-time.png"},"nutrition-label":{"name":"Nutrition Label","size":[946,1663],"crop":[217,11,512,1641],"slots":[{"x":250,"y":356,"w":446,"h":281,"r":0},{"x":250,"y":655,"w":446,"h":281,"r":0},{"x":250,"y":953,"w":446,"h":281,"r":0}],"src":"public/a-nutrition-label.png"},"red-music-player":{"name":"Red Music Player","size":[1123,1401],"crop":[300,9,524,1382],"slots":[{"x":345,"y":53,"w":435,"h":284,"r":28},{"x":345,"y":354,"w":435,"h":284,"r":28},{"x":345,"y":655,"w":435,"h":284,"r":28}],"src":"public/a-red-music-player.png"},"story-today":{"name":"Story Today","size":[1063,1479],"crop":[246,4,570,1471],"slots":[{"x":273,"y":272,"w":517,"h":282,"r":0},{"x":273,"y":569,"w":517,"h":282,"r":0},{"x":273,"y":864,"w":517,"h":274,"r":0}],"src":"public/a-story-today.png"},"ticket-memories":{"name":"Ticket Memories","size":[957,1644],"crop":[24,7,437,1472],"slots":[{"x":64,"y":318,"w":356,"h":271,"r":0},{"x":64,"y":602,"w":356,"h":270,"r":0},{"x":64,"y":886,"w":356,"h":268,"r":0}],"src":"public/a-ticket-memories.png"}};
  const screen=document.querySelector('#flow-screen'),dialog=document.querySelector('#instructions');
  const colors={cherry:['#a82e3e','#fff7ec'],cream:['#faf6ea','#262a27'],ink:['#292b2a','#faf6ea'],blue:['#c1d6e3','#262a27']};
  const state={step:'layout',layout:'A',shots:[],filter:'original',color:'cherry',design:'classic',template:null,caption:'better together.',mode:'sample',stream:null,busy:false,generation:0,method:'timer',seconds:3,retake:null};
  let timer,active=false,renderVersion=0,cameraRequest=0,cameraPending=false,exporting=false,previewTimer;
  const $=s=>screen.querySelector(s);
  const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const heading=(k,t,n)=>`<div class="flow-heading"><div class="eyebrow">${k}</div><h1 tabindex="-1">${t}</h1><p>${n}</p></div>`;
  const countReady=()=>state.shots.filter(Boolean).length;
  const complete=()=>countReady()===layouts[state.layout].count;
  function stopCamera(){cameraRequest++;cameraPending=false;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.mode='sample'}
  function cancelCapture(){clearTimeout(timer);state.generation++;state.busy=false}
  function showStep(step){cancelCapture();renderVersion++;state.step=step;document.querySelectorAll('[data-step]').forEach(el=>{const current=el.dataset.step===step;el.classList.toggle('current',current);current?el.setAttribute('aria-current','step'):el.removeAttribute('aria-current')});({layout:layoutScreen,design:designScreen,session:sessionScreen,edit:editorScreen})[step]();screen.querySelector('h1')?.focus({preventScroll:true});window.scrollTo(0,0)}
  function miniature(l){return `<span class="reference-mini ${l.width>l.height?'landscape':l.width===600?'narrow':'portrait'}" style="aspect-ratio:${l.width}/${l.height}">${l.slots.map((r,i)=>`<i style="left:${r.x*100}%;top:${r.y*100}%;width:${r.w*100}%;height:${r.h*100}%">${i+1}</i>`).join('')}</span>`}
  function layoutScreen(){screen.innerHTML=heading('FIRST, A LITTLE SHAPE','Every memory needs <em>a frame.</em>','Eight ways to keep a moment. Choose your size and arrangement.')+`<fieldset class="layout-picker reference-picker"><legend class="sr-only">Photocard layout</legend>${Object.entries(layouts).filter(([key])=>!["F","I","J"].includes(key)).map(([key,l])=>`<label class="layout-option"><input type="radio" name="layout" value="${key}" ${state.layout===key?'checked':''}><span class="layout-choice"><span class="mini-stage">${miniature(l)}</span><strong>${l.name}</strong><span>${l.note}</span><small>${l.label}</small><span class="layout-check" aria-hidden="true">✓</span></span></label>`).join('')}</fieldset><div class="step-actions"><p>We’ll take exactly the number of photos your layout needs.</p><button class="primary" id="start-session">Choose a design <span aria-hidden="true">↗</span></button></div>`;let chosen=state.layout;screen.querySelectorAll('[name=layout]').forEach(r=>r.onchange=()=>chosen=r.value);$('#start-session').onclick=()=>{if(chosen!==state.layout){state.shots=[];state.template=null;state.layout=chosen}state.retake=null;showStep('design')}}

  function designScreen(){const isA=state.layout==='A';
    screen.innerHTML=heading('NEXT, A LITTLE PERSONALITY','A design that feels <em>like you.</em>',isA?'Layout A · 3 photos · Choose your photocard before the camera starts.':'More designs for this layout are coming later. You can use the classic frame today.')+
    '<fieldset class="card-design-gallery"><legend class="sr-only">Choose photocard design</legend>'+ (isA?Object.entries(cardDesigns).map(([key,d])=>{const [x,y,w,h]=d.crop;return `<label class="card-design-option"><input type="radio" name="card-template" value="${key}" ${state.template===key?'checked':''}><span class="card-design-face"><span class="card-art-window" style="aspect-ratio:${w}/${h}"><img src="${d.src}" alt="${d.name} three-photo design" loading="lazy" style="width:${d.size[0]/w*100}%;height:${d.size[1]/h*100}%;left:${-x/w*100}%;top:${-y/h*100}%"></span><strong>${d.name}</strong><small>3 photos</small></span></label>`}).join(''):'')+
    `<label class="card-design-option"><input type="radio" name="card-template" value="classic" ${!state.template?'checked':''}><span class="card-design-face"><span class="plain-design-thumb">${miniature(layouts[state.layout])}</span><strong>Classic</strong><small>Your colors, your caption</small></span></label></fieldset><div class="step-actions"><button class="text-button" id="back-layout">← Change layout</button><button class="primary" id="design-continue">Take the photos now ↗</button></div>`;
    screen.querySelectorAll('[name=card-template]').forEach(r=>r.onchange=()=>{state.template=r.value==='classic'?null:r.value});
    $('#back-layout').onclick=()=>showStep('layout');$('#design-continue').onclick=()=>showStep('session');
  }
  function photoTray(){const l=layouts[state.layout];return `<div class="photo-review"><div class="review-heading"><strong>Your photos</strong><span>${countReady()} / ${l.count}</span></div><p>Drag photos to reorder, or use the arrow buttons. Retake only the one you want to change.</p><div class="review-photos">${Array.from({length:l.count},(_,i)=>`<article class="review-photo ${state.retake===i?'selected-retake':''}" data-shot="${i}" ${state.shots[i]?'draggable="true"':''}><div class="review-image">${state.shots[i]?`<img src="${state.shots[i]}" alt="Photo ${i+1}" draggable="false">`:`<span>${i+1}</span>`}<b>${i+1}</b></div>${state.shots[i]?`<div class="reorder-controls"><button data-move="${i}" data-direction="-1" aria-label="Move photo ${i+1} earlier" ${i===0?'disabled':''}>←</button><button class="drag-handle" aria-label="Drag photo ${i+1} to reorder">⠿</button><button data-move="${i}" data-direction="1" aria-label="Move photo ${i+1} later" ${i===l.count-1||!state.shots[i+1]?'disabled':''}>→</button></div><button class="retake-button" data-retake="${i}">Retake photo ${i+1}</button>`:'<span class="empty-photo-label">Waiting for a moment</span>'}</article>`).join('')}</div><p id="order-status" class="session-note" role="status"></p></div>`}
  function bindPhotoTray(){
    const reorder=(from,to)=>{if(state.busy||cameraPending||from===to||!state.shots[from]||!state.shots[to])return;state.shots=move(state.shots,from,to);state.retake=null;state.step==='edit'?editorScreen():sessionScreen();$('#order-status').textContent=`Photo ${from+1} moved to position ${to+1}.`;screen.querySelector(`[data-shot="${to}"] .drag-handle`)?.focus({preventScroll:true})};
    screen.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>reorder(Number(b.dataset.move),Number(b.dataset.move)+Number(b.dataset.direction)));
    screen.querySelectorAll('[data-retake]').forEach(b=>b.onclick=()=>{state.retake=Number(b.dataset.retake);const restoreCamera=state.step==='edit'&&state.returnToCamera;if(state.step!=='session')showStep('session');else sessionScreen();if(restoreCamera)toggleCamera();$('#capture-session').focus({preventScroll:true})});
    let from=null;
    screen.querySelectorAll('[data-shot]').forEach(card=>{card.ondragstart=e=>{if(state.busy||cameraPending){e.preventDefault();return}from=Number(card.dataset.shot);e.dataTransfer.setData('text/plain',String(from));e.dataTransfer.effectAllowed='move'};card.ondragover=e=>{if(from!==null&&state.shots[Number(card.dataset.shot)]){e.preventDefault();e.dataTransfer.dropEffect='move'}};card.ondrop=e=>{e.preventDefault();if(from!==null)reorder(from,Number(card.dataset.shot));from=null};card.ondragend=()=>from=null});
    screen.querySelectorAll('.drag-handle').forEach(handle=>{let pointer=null;handle.onpointerdown=e=>{if(e.pointerType==='mouse'||state.busy||cameraPending)return;pointer={id:e.pointerId,from:Number(handle.closest('[data-shot]').dataset.shot)};handle.setPointerCapture(e.pointerId);handle.closest('[data-shot]').classList.add('dragging')};handle.onpointermove=e=>{if(!pointer)return;e.preventDefault();screen.querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-shot]')?.classList.add('drop-target')};const finish=e=>{if(!pointer)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-shot]');const start=pointer.from;pointer=null;screen.querySelectorAll('.drop-target,.dragging').forEach(el=>el.classList.remove('drop-target','dragging'));if(e.type==='pointerup'&&target)reorder(start,Number(target.dataset.shot))};handle.onpointerup=finish;handle.onpointercancel=finish});
  }
  function sessionScreen(){const l=layouts[state.layout];screen.innerHTML=heading('NOW, YOUR LITTLE MOMENT','A smile. A silly face. <em>You.</em>',`${l.name} · ${l.note}. Your favorite moments, at your own pace.`)+`<div class="session-surface"><div class="session-bar"><span>${state.mode==='camera'?'Solo camera session':'Sample session'}</span><button class="text-button" id="camera-toggle">${state.mode==='camera'?'Use sample photos':'Turn camera on'}</button></div><div class="session-view"><div class="sample-pair" ${state.mode==='camera'?'hidden':''}><img src="public/woman.jpg" alt="Sample portrait"><img src="public/man.jpg" alt="Sample portrait"></div><video id="live-camera" autoplay muted playsinline ${state.mode==='camera'?'':'hidden'}></video><div id="shot-countdown" hidden aria-live="assertive"></div></div><p id="camera-message" class="session-note" role="status">${state.mode==='camera'?'Camera on. Photos stay in this browser tab.':'Try sample portraits, or turn on your camera for real solo photos.'}</p><div class="capture-settings"><fieldset><legend>HOW SHALL WE TAKE THEM?</legend><label><input type="radio" name="capture-method" value="timer" ${state.method==='timer'?'checked':''}> With a timer</label><label><input type="radio" name="capture-method" value="manual" ${state.method==='manual'?'checked':''}> Manual click</label></fieldset><label class="timer-setting" ${state.method==='manual'?'hidden':''}>COUNTDOWN<select id="timer-seconds"><option value="3" ${state.seconds===3?'selected':''}>3 seconds</option><option value="5" ${state.seconds===5?'selected':''}>5 seconds</option><option value="7" ${state.seconds===7?'selected':''}>7 seconds</option></select></label></div><p id="session-status" aria-live="polite">${state.retake!==null?`Retaking photo ${state.retake+1}. Your other photos will stay exactly as they are.`:complete()?'All photos are ready. Reorder, retake, or make your card yours.':state.method==='manual'?'One click takes one photo, with no countdown.':`A ${state.seconds}-second countdown before each remaining photo.`}</p><div class="session-buttons"><button class="text-button" id="change-layout">← Change design</button>${state.retake!==null?'<button class="text-button" id="cancel-retake">Cancel retake</button>':''}<button class="primary" id="capture-session" ${complete()&&state.retake===null?'disabled':''}>${state.retake!==null?`Retake photo ${state.retake+1}`:state.method==='manual'?'Take a photo':countReady()?'Continue countdown':'Start the countdown'} <span aria-hidden="true">◎</span></button><button class="outline-button" id="stop-capture" hidden>Stop countdown</button><button class="secondary" id="to-editor" ${complete()&&state.retake===null?'':'disabled'}>Make it yours →</button></div>${photoTray()}</div>`;
    if(state.stream)$('#live-camera').srcObject=state.stream;
    $('#camera-toggle').onclick=toggleCamera;$('#change-layout').onclick=()=>{stopCamera();showStep('design')};$('#capture-session').onclick=startCapture;$('#stop-capture').onclick=()=>{cancelCapture();sessionScreen();$('#session-status').textContent='Countdown stopped. Your captured photos are saved.'};$('#cancel-retake')?.addEventListener('click',()=>{state.retake=null;sessionScreen()});
    $('#to-editor').onclick=()=>{if(complete()){state.returnToCamera=state.mode==='camera';stopCamera();state.retake=null;showStep('edit')}};
    screen.querySelectorAll('[name=capture-method]').forEach(r=>r.onchange=()=>{state.method=r.value;sessionScreen()});$('#timer-seconds').onchange=e=>{state.seconds=Number(e.target.value);sessionScreen()};bindPhotoTray();lockSession();
  }
  function lockSession(){if(state.step!=='session')return;screen.querySelectorAll('button,input,select').forEach(el=>{if(state.busy||cameraPending)el.disabled=true});if(state.busy){$('#stop-capture').hidden=false;$('#stop-capture').disabled=false}}
  async function toggleCamera(){if(state.stream){stopCamera();sessionScreen();return}const request=++cameraRequest;cameraPending=true;lockSession();$('#camera-message').textContent='Waiting for camera permission…';try{if(!navigator.mediaDevices?.getUserMedia)throw Error('unavailable');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});if(request!==cameraRequest||!active||state.step!=='session'){stream.getTracks().forEach(t=>t.stop());return}state.stream=stream;state.mode='camera';cameraPending=false;sessionScreen()}catch(e){if(request!==cameraRequest||state.step!=='session')return;cameraPending=false;sessionScreen();$('#camera-message').textContent=e.name==='NotAllowedError'?'Camera permission was not granted. Try again or use sample photos.':'The camera isn’t available. Check that it’s connected and not in use, or try sample photos.'}}
  const loadImage=src=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src});
  function cover(ctx,img,x,y,w,h){const iw=img.videoWidth||img.naturalWidth,ih=img.videoHeight||img.naturalHeight;const scale=Math.max(w/iw,h/ih);ctx.drawImage(img,(iw-w/scale)/2,(ih-h/scale)/2,w/scale,h/scale,x,y,w,h)}
  async function takeShot(){const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=960;const ctx=canvas.getContext('2d');if(state.mode==='camera'){const video=$('#live-camera');if(!video?.videoWidth)throw Error('The camera is still warming up. Please try again.');canvas.height=Math.round(canvas.width*video.videoHeight/video.videoWidth);ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.drawImage(video,0,0,canvas.width,canvas.height)}else{const images=await Promise.all([loadImage('public/woman.jpg'),loadImage('public/man.jpg')]);cover(ctx,images[0],0,0,717,960);cover(ctx,images[1],723,0,717,960)}return canvas.toDataURL('image/jpeg',.95)}
  function startCapture(){if(state.busy||cameraPending)return;const targets=captureTargets(state.shots,layouts[state.layout].count,state.retake,state.method==='manual');if(!targets.length)return;state.busy=true;const generation=++state.generation;lockSession();let position=0;const countdown=$('#shot-countdown');
    async function capture(){try{const shot=await takeShot();if(generation!==state.generation)return;state.shots=replaceShot(state.shots,targets[position],shot);position++;if(position===targets.length){state.busy=false;state.retake=null;sessionScreen();$('#session-status').textContent=complete()?'All photos are ready. Drag to reorder or retake a single photo.':`${countReady()} photos ready. Take the next when you’re ready.`;return}countdown.textContent='♡';timer=setTimeout(begin,500)}catch(e){if(generation!==state.generation)return;state.busy=false;sessionScreen();$('#camera-message').textContent=e.message}}
    function begin(){if(generation!==state.generation)return;let remaining=state.method==='manual'?0:state.seconds;function tick(){if(generation!==state.generation)return;$('#session-status').textContent=`Taking photo ${targets[position]+1} of ${layouts[state.layout].count}`;if(remaining===0){countdown.hidden=true;capture();return}countdown.hidden=false;countdown.textContent=remaining--;timer=setTimeout(tick,1000)}tick()}begin();
  }
  function editorScreen(){const l=layouts[state.layout];screen.innerHTML=heading('YOUR FINISHED MOMENTS','Your photos. <em>Your keepsake.</em>',`${l.name} · ${l.note}. Add the finishing touches.`)+`<div class="finish-grid"><div class="final-preview"><img id="card-preview" alt="Your photocard preview"><p id="preview-status" role="status">Preparing your photocard…</p></div><div class="finish-controls"><div class="chosen-design-note"><strong>${state.template?cardDesigns[state.template].name:"Classic"}</strong><button class="text-button" id="review-change-design">Change design</button></div><fieldset><legend>FRAME COLOR</legend><div class="swatches">${Object.entries(colors).map(([key,c])=>`<button class="swatch ${state.color===key?'active':''}" data-color="${key}" aria-label="${key}" aria-pressed="${state.color===key}" style="--swatch:${c[0]}"></button>`).join('')}</div></fieldset><fieldset><legend>PHOTO FILTER</legend><div class="filter-options">${Object.entries(filters).map(([key,name])=>`<button class="filter ${state.filter===key?'active':''}" data-filter="${key}" aria-pressed="${state.filter===key}">${name}</button>`).join('')}</div></fieldset><label class="caption-label" for="card-caption">A FEW WORDS TO KEEP</label><input id="card-caption" maxlength="28" value="${escape(state.caption)}"><p class="session-note">Filters apply to the photos. Your original captures stay unchanged.</p><button class="text-button" id="back-session">← Back to your photos</button></div></div>${photoTray()}<div class="finish-bottom"><div><strong>Keep this little moment.</strong><p>${l.width} × ${l.height} pixels. Print at ${l.width/300} × ${l.height/300} inches with 100% scaling.</p></div><div class="finish-buttons"><button class="outline-button" id="print-card">Print ↗</button><label class="sr-only" for="export-format">Download format</label><select id="export-format"><option value="png">PNG</option><option value="jpeg">JPG</option></select><button class="primary" id="download-card">Download ↓</button></div><p id="export-status" role="status"></p></div>`;
    screen.querySelectorAll('[name=design]').forEach(r=>r.onchange=()=>{state.design=r.value;updatePreview()});for(const type of ['color','filter'])screen.querySelectorAll(`[data-${type}]`).forEach(b=>b.onclick=()=>{state[type]=b.dataset[type];screen.querySelectorAll(`[data-${type}]`).forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b))});updatePreview()});$('#card-caption').oninput=e=>{state.caption=e.target.value;clearTimeout(previewTimer);renderVersion++;previewTimer=setTimeout(updatePreview,120)};$('#review-change-design').onclick=()=>showStep('design');if(state.template){screen.querySelectorAll('[data-color]').forEach(b=>b.closest('fieldset').hidden=true);$('#card-caption').hidden=true;screen.querySelector('label[for=card-caption]').hidden=true;screen.querySelector('.finish-controls .session-note').textContent='Your selected design is ready. Filters apply only to your photos; the printed artwork stays unchanged.'}$('#back-session').onclick=()=>showStep('session');$('#download-card').onclick=()=>exportCard(false);$('#print-card').onclick=()=>exportCard(true);bindPhotoTray();updatePreview();
  }

  async function renderDesignedCard(){
    const snapshot={...state,shots:[...state.shots]},d=cardDesigns[snapshot.template];if(snapshot.shots.length!==3)throw Error('Three photos required');
    const [art,...images]=await Promise.all([loadImage(d.src),...snapshot.shots.map(loadImage)]);
    const canvas=document.createElement('canvas');canvas.width=600;canvas.height=1800;const ctx=canvas.getContext('2d');
    const [cx,cy,cw,ch]=d.crop,scale=Math.min(600/cw,1800/ch),ox=(600-cw*scale)/2,oy=(1800-ch*scale)/2;
    ctx.fillStyle='#fff';ctx.fillRect(0,0,600,1800);ctx.drawImage(art,cx,cy,cw,ch,ox,oy,cw*scale,ch*scale);
    images.forEach((img,i)=>{const r=d.slots[i],w=Math.round(r.w*scale),h=Math.round(r.h*scale),photo=document.createElement('canvas');photo.width=w;photo.height=h;const pc=photo.getContext('2d',{willReadFrequently:true});cover(pc,img,0,0,w,h);
      if(snapshot.filter!=='original'){const pixels=pc.getImageData(0,0,w,h);filterPixels(pixels.data,snapshot.filter,17+i);pc.putImageData(pixels,0,0)}
      if(d.mask==='cream'){const mask=document.createElement('canvas');mask.width=w;mask.height=h;const mc=mask.getContext('2d',{willReadFrequently:true});mc.drawImage(art,r.x,r.y,r.w,r.h,0,0,w,h);const mp=mc.getImageData(0,0,w,h);for(let p=0;p<mp.data.length;p+=4)mp.data[p+3]=(mp.data[p]>215&&mp.data[p+1]>205&&mp.data[p+2]>175)?255:0;mc.putImageData(mp,0,0);pc.globalCompositeOperation='destination-in';pc.drawImage(mask,0,0)}
      const x=ox+(r.x-cx)*scale,y=oy+(r.y-cy)*scale;ctx.save();ctx.beginPath();if(r.poly){r.poly.forEach(([px,py],n)=>{const dx=ox+(px-cx)*scale,dy=oy+(py-cy)*scale;n?ctx.lineTo(dx,dy):ctx.moveTo(dx,dy)});ctx.closePath()}else ctx.roundRect(x,y,w,h,(r.r||0)*scale);ctx.clip();ctx.drawImage(photo,x,y,w,h);ctx.restore();
    });return canvas;
  }
  async function renderCard(){if(state.template&&state.layout==='A')return renderDesignedCard();const snapshot={...state,shots:[...state.shots]},l=layouts[snapshot.layout],canvas=document.createElement('canvas');canvas.width=l.width;canvas.height=l.height;const ctx=canvas.getContext('2d'),[bg,fg]=colors[snapshot.color];const images=await Promise.all(snapshot.shots.map(loadImage));await document.fonts.ready;ctx.fillStyle=bg;ctx.fillRect(0,0,l.width,l.height);
    images.forEach((img,i)=>{const r=l.slots[i],x=Math.round(r.x*l.width),y=Math.round(r.y*l.height),w=Math.round(r.w*l.width),h=Math.round(r.h*l.height);const photo=document.createElement('canvas');photo.width=w;photo.height=h;const pc=photo.getContext('2d',{willReadFrequently:true});cover(pc,img,0,0,w,h);if(snapshot.filter!=='original'){const pixels=pc.getImageData(0,0,w,h);filterPixels(pixels.data,snapshot.filter,17+i);pc.putImageData(pixels,0,0)}ctx.drawImage(photo,x,y);if(snapshot.design==='outline'){ctx.strokeStyle=fg;ctx.lineWidth=2;ctx.strokeRect(x+5,y+5,w-10,h-10)}});
    const a=l.caption,cx=(a.x+a.w/2)*l.width,cy=(a.y+a.h/2)*l.height,available=a.w*l.width-18;ctx.fillStyle=fg;ctx.textAlign='center';let size=Math.min(66,a.h*l.height*.33);ctx.font=`italic ${size}px "Instrument Serif", Georgia`;while(ctx.measureText(snapshot.caption).width>available&&size>12){ctx.font=`italic ${--size}px "Instrument Serif", Georgia`}ctx.fillText(snapshot.caption,cx,cy+size*.12);if(a.h*l.height>130){ctx.font=`500 ${Math.min(20,a.w*l.width/23)}px "DM Sans", Arial`;ctx.fillText('T O G E T H E R',cx,cy+size*.9+16)}if(snapshot.design==='hearts'){ctx.font=`${Math.min(30,a.h*l.height*.18)}px Georgia`;ctx.fillText('♡',cx,cy-size*.7)}return canvas;
  }
  async function updatePreview(){const version=++renderVersion;try{const canvas=await renderCard();if(version!==renderVersion||state.step!=='edit')return;$('#card-preview').src=canvas.toDataURL('image/png');$('#preview-status').textContent='Your layout, photo order and filter are included in the download.'}catch{if(version===renderVersion&&state.step==='edit')$('#preview-status').textContent='We couldn’t render the preview. Please try your photos again.'}}
  async function exportCard(print){if(exporting)return;exporting=true;const status=$('#export-status'),l=layouts[state.layout],format=$('#export-format').value;$('#download-card').disabled=$('#print-card').disabled=true;status.textContent=print?'Preparing your print…':'Preparing your download…';try{const canvas=await renderCard();if(print){const sheet=document.querySelector('#print-sheet'),img=new Image();img.alt='Your finished Together photocard';img.src=canvas.toDataURL('image/png');img.style.width=`${l.width/300}in`;img.style.height=`${l.height/300}in`;await img.decode();sheet.replaceChildren(img);window.print();status.textContent='Print dialog requested. Choose 100% scaling to keep the card size.'}else{const blob=await new Promise(resolve=>canvas.toBlob(resolve,`image/${format}`,.95));if(!blob)throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`together-layout-${l.id}.${format==='jpeg'?'jpg':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Your photocard is ready to keep.'}}catch{status.textContent='Something went wrong. Please try again.'}finally{exporting=false;if(state.step==='edit')$('#download-card').disabled=$('#print-card').disabled=false}}
  function showInstructions(){if(state.busy){cancelCapture();sessionScreen()}if(!dialog.open)dialog.showModal()}
  document.querySelector('#show-instructions').onclick=showInstructions;document.querySelector('.dialog-close').onclick=()=>{dialog.close();if(state.step==='layout')location.hash=''};document.querySelector('#instructions-continue').onclick=()=>{dialog.close();screen.querySelector('h1')?.focus({preventScroll:true})};dialog.addEventListener('cancel',()=>{if(state.step==='layout')location.hash=''});
  window.addEventListener('booth-route',e=>{const entering=e.detail.active&&!active;active=e.detail.active;if(entering){showStep('layout');showInstructions()}if(!active){cancelCapture();stopCamera();renderVersion++;if(dialog.open)dialog.close()}});window.addEventListener('pagehide',()=>{cancelCapture();stopCamera()});if(location.hash==='#booth'){active=true;showStep('layout');showInstructions()}
})();
