const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => Number(n).toLocaleString('en-US');
export function paymentEmail(job, config) {
 const p=job.payload, admin=job.event==='pending', approved=job.event==='approved';
 const origin=new URL(config.siteUrl); if(origin.protocol!=='https:') throw new Error('HTTPS site URL required');
 const base=origin.origin;
 const panel=`${base}/?order=${encodeURIComponent(p.orderId)}#account/admin`;
 const title=admin?'Payment awaiting review':approved?'Points Added':'Payment Unsuccessful';
 const badge=admin?'PENDING REVIEW':approved?'APPROVED':'NOT APPROVED';
 const color=approved?'#246344':admin?'#805c18':'#a82c3c';
 const intro=admin?`${p.name} submitted a payment. Verify the incoming transfer in KBZPay before approving.`:approved?`Your payment was approved. ${money(p.points)} points have been added to your account.`:'We could not approve this payment. No points were added. Please check the details below or contact us.';
 const rows=[['Order ID',p.orderId],['Date',new Date(p.date).toLocaleString('en-GB',{timeZone:'Asia/Yangon'})+' (Myanmar time)'],['Amount',money(p.amount)+' MMK'],[approved?'Points credited':'Points requested',money(p.points)]];
 if(approved)rows.push(['Balance after approval',money(p.balance)+' points']);
 if(admin)rows.unshift(['Customer',p.name],['Email',p.email],['User ID',p.userId]);
 if(p.reference)rows.push(['Payment reference',p.reference]);
 if(!admin&&!approved)rows.push(['Reason',p.reason||'Please contact support for help with this payment.']);
 const button=(label,url,bg='#a82c3c')=>`<a href="${escape(url)}" style="display:inline-block;background:${bg};color:#ffffff;padding:15px 22px;border-radius:8px;text-decoration:none;font-weight:bold;margin:6px 4px">${escape(label)}</a>`;
 const actions=admin?button('Approve',panel.replace('#','&action=approve#'))+button('Reject',panel.replace('#','&action=reject#'),'#252b26')+`<p><a href="${escape(panel)}" style="color:#a82c3c">View payment reference / receipt securely</a></p>`:button(approved?'Open Photobooth':'Contact Support',approved?`${base}/#booth`:`mailto:${config.supportEmail}`);
 const logo=config.logoUrl?`<img src="${escape(config.logoUrl)}" width="180" alt="Together Photobooth" style="max-width:100%;height:auto;border:0">`:'<span style="font-size:36px;letter-spacing:-2px;color:#252b26">together <span style="color:#a82c3c">✳</span></span>';
 const html=`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8"><title>${title}</title></head><body style="margin:0;background:#f5f1e8;color:#252b26;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px"><tr><td align="center" style="padding:20px">${logo}<p style="font-size:13px;color:#6d7468">Your people. Any distance.</p></td></tr><tr><td style="background:#fffdf7;border:1px solid #deded2;border-radius:16px;padding:28px"><span style="display:inline-block;color:${color};background:#f1f1e7;padding:7px 12px;border-radius:20px;font-size:12px;font-weight:bold">${badge}</span><h1 style="font-size:28px;line-height:1.2;margin:20px 0">${title}</h1><p style="line-height:1.7">${escape(intro)}</p><table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;table-layout:fixed">${rows.map(([k,v])=>`<tr><th scope="row" align="left" style="width:38%;padding:12px 6px;border-bottom:1px solid #e5e3d9;font-size:13px;vertical-align:top">${escape(k)}</th><td style="padding:12px 6px;border-bottom:1px solid #e5e3d9;font-size:13px;overflow-wrap:anywhere;word-break:break-word">${escape(v)}</td></tr>`).join('')}</table><div style="text-align:center;padding-top:22px">${actions}</div>${admin?'<p style="font-size:12px;line-height:1.6;color:#6d7468">These links open the admin panel. Sign in and confirm your decision there. Opening an email never approves a payment.</p>':''}</td></tr><tr><td align="center" style="padding:24px;font-size:12px;line-height:1.8;color:#6d7468">Need help? <a style="color:#a82c3c" href="mailto:${escape(config.supportEmail)}">${escape(config.supportEmail)}</a><br>© ${new Date(p.date).getUTCFullYear()} Together Photobooth · <a href="${base}" style="color:#6d7468">Website</a> · <a href="${base}/#account" style="color:#6d7468">My account</a></td></tr></table></td></tr></table></body></html>`;
 return {subject:`Together — ${title}`,html,text:[title,intro,...rows.map(([k,v])=>`${k}: ${v}`),admin?panel:`${base}/#account`,`Support: ${config.supportEmail}`].join('\n')};
}
