const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const box={};vm.createContext(box);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../booth-core.js'),'utf8'),box);const core=box.BoothCore;
const expected=[3,4,4,1,2,1,2,4,3,3,2];
function separated(a,b){return a.x+a.w<=b.x+1e-9||b.x+b.w<=a.x+1e-9||a.y+a.h<=b.y+1e-9||b.y+b.h<=a.y+1e-9}
for(const [i,l] of Object.values(core.layouts).entries()){assert.equal(l.count,expected[i]);assert([1/3,2/3,1.5].includes(l.width/l.height));for(const r of l.slots){assert(r.x>=0&&r.y>=0&&r.x+r.w<=1&&r.y+r.h<=1);assert(separated(r,l.caption),'Caption must stay in reserved space')}for(let a=0;a<l.count;a++)for(let b=a+1;b<l.count;b++)assert(separated(l.slots[a],l.slots[b]),'Photo slots overlap')}
assert.deepEqual([...core.move(['a','b','c','d'],3,0)],['d','a','b','c']);assert.deepEqual([...core.replaceShot(['a','b','c','d'],1,'NEW')],['a','NEW','c','d']);
const pixels=new Uint8ClampedArray(Array.from({length:200},()=>[130,110,90,255]).flat());const original=pixels.slice();core.filterPixels(pixels,'original');assert.deepEqual(pixels,original);
for(const key of Object.keys(core.filters).filter(k=>k!=='original')){const data=original.slice();core.filterPixels(data,key);assert.notDeepEqual(data,original);for(let i=3;i<data.length;i+=4)assert.equal(data[i],255)}
const g1=original.slice(),g2=original.slice();core.filterPixels(g1,'vintage',17);core.filterPixels(g2,'vintage',17);assert.deepEqual(g1,g2);assert(new Set(Array.from(g1).filter((_,i)=>i%4===0)).size>5,'Grain must vary across pixels');
const code=fs.readFileSync(require('path').join(__dirname,'../booth-flow.js'),'utf8');const captureCode=code.slice(code.indexOf('function startCapture()'),code.indexOf('function editorScreen()'));
function harness(method,seconds,shots=[],retake=null){let now=0,id=0;const jobs=new Map(),times=[];const s={layout:'B',shots:[...shots],method,seconds,retake,busy:false,generation:0};const nodes={};const ctx={state:s,layouts:core.layouts,captureTargets:core.captureTargets,replaceShot:core.replaceShot,cameraPending:false,timer:null,$:q=>nodes[q]??=( {} ),lockSession:()=>{},sessionScreen:()=>{},complete:()=>s.shots.filter(Boolean).length===4,countReady:()=>s.shots.filter(Boolean).length,takeShot:async()=>{times.push(now);return `new-${times.length}`},setTimeout:(fn,delay)=>{jobs.set(++id,{fn,time:now+delay});return id}};vm.createContext(ctx);vm.runInContext(captureCode,ctx);return {s,ctx,times,start:()=>vm.runInContext('startCapture()',ctx),async drain(){for(let n=0;n<100;n++){await Promise.resolve();await Promise.resolve();if(!jobs.size){await Promise.resolve();if(!jobs.size)return}const [key,job]=[...jobs].sort((a,b)=>a[1].time-b[1].time)[0];jobs.delete(key);now=job.time;job.fn()}throw Error('Capture did not terminate')}}}
(async()=>{
for(const seconds of [3,5,7]){const h=harness('timer',seconds,['kept']);h.start();await h.drain();assert.equal(h.s.shots.length,4);assert.equal(h.s.shots[0],'kept');assert.deepEqual(h.times,[seconds*1000,seconds*2000+500,seconds*3000+1000]);assert.equal(h.s.busy,false)}
const manual=harness('manual',7,['kept']);manual.start();await manual.drain();assert.deepEqual([...manual.s.shots],['kept','new-1']);assert.deepEqual(manual.times,[0]);
const retake=harness('timer',5,['a','b','c','d'],1);retake.start();await retake.drain();assert.deepEqual([...retake.s.shots],['a','new-1','c','d']);assert.deepEqual(retake.times,[5000]);
const failed=harness('manual',3,['a','b','c','d'],1);failed.ctx.takeShot=async()=>{throw Error('Camera failure')};failed.start();await failed.drain();assert.deepEqual([...failed.s.shots],['a','b','c','d']);
const cancelled=harness('timer',3,['kept']);cancelled.start();cancelled.s.generation++;await cancelled.drain();assert.deepEqual([...cancelled.s.shots],['kept']);assert.equal(cancelled.times.length,0);
const full=harness('manual',3,['a','b','c','d']);full.start();await full.drain();assert.equal(full.times.length,0);
console.log('PASS: 11 reference layouts, ratios, slot/caption bounds; reorder and single replacement; six filters and repeatable grain; actual capture controller at 3/5/7 seconds, manual capture, single retake, failed retake preservation, cancellation and full-layout limit.');
})().catch(e=>{console.error(e);process.exit(1)});
