const escape = (value: string) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function authEmail(action: string, link: string, logo: string, support: string, token = '') {
 const reset=action==='recovery', verify=action==='signup';
 const title=reset?'A fresh password.':verify?'Welcome to Together.':action==='reauthentication'?'Confirm it’s you.':'Confirm your account action.';
 const label=reset?'Reset password':verify?'Verify my email':'Continue securely';
 const description=reset?'Use the secure link below to choose a new password.':verify?'Confirm your email to start making little memories together.':'You requested a secure account action. Continue below to complete it.';
 return {subject:reset?'Reset your Together password':verify?'Verify your Together account':'Confirm your Together account action',
 html:`<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;background:#f5f2e9;font-family:Arial,sans-serif;color:#262d27"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" style="max-width:600px;background:#fffdf7;border:1px solid #deded3;border-radius:16px"><tr><td style="padding:32px;text-align:center"><img src="${escape(logo)}" width="180" alt="Together" style="max-width:100%;height:auto"><p style="font-size:12px;letter-spacing:2px;color:#747a6f">YOUR PEOPLE. ANY DISTANCE.</p><h1 style="font-size:30px">${title}</h1><p style="line-height:1.7">${description}</p>${action==='reauthentication'?`<p style="font-size:30px;letter-spacing:6px">${escape(token)}</p>`:`<a href="${escape(link)}" style="display:inline-block;padding:16px 28px;background:#ae2940;border-radius:8px;color:white;text-decoration:none;font-weight:bold">${label}</a>`}<p style="font-size:13px;line-height:1.7;color:#747a6f">This is a single-use link or code. It expires according to our account security settings. Please use the newest email promptly.</p><p style="font-size:13px;line-height:1.7">If you didn’t request this, ignore this email. Never share your password, verification link, or code.</p><hr style="border:0;border-top:1px solid #deded3"><p style="font-size:12px">Need help? <a href="mailto:${escape(support)}">${escape(support)}</a><br>© ${new Date().getUTCFullYear()} Together</p></td></tr></table></td></tr></table></body></html>`,
 text:`${title}\n${description}\n${action==='reauthentication'?token:link}\nUse the newest email promptly. This link or code expires and can only be used once. If you did not request this, ignore this email. Support: ${support}`};
}
